# Generated by Django 5.0 on 2024-06-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('drink_type', models.CharField(choices=[('espresso', 'espresso'), ('latte', 'latte'), ('cappuccino', 'Cappuccino'), ('americano', 'Americano'), ('cocacola', 'Cocacola'), ('sprite', 'Sprite'), ('fanta', 'Fanta'), ('milkshake', 'Milkshake'), ('mango_juice', 'Mango Juice'), ('passion_juice', 'Passion Juice')], max_length=50)),
                ('size', models.CharField(choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large')], max_length=50)),
                ('total_price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
